services:
  - type: web
    name: worklife-balancer
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 14.21.3
      - key: NODE_ENV
        value: production
